# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 7) do

  create_table "comments", :force => true do |t|
    t.column "comment",          :text,                   :default => ""
    t.column "created_at",       :datetime,                               :null => false
    t.column "commentable_id",   :integer,                :default => 0,  :null => false
    t.column "commentable_type", :string,   :limit => 15, :default => "", :null => false
    t.column "user_id",          :integer,                :default => 0,  :null => false
  end

  create_table "geocodes", :force => true do |t|
    t.column "latitude",    :decimal, :precision => 15, :scale => 12
    t.column "longitude",   :decimal, :precision => 15, :scale => 12
    t.column "query",       :string
    t.column "street",      :string
    t.column "locality",    :string
    t.column "region",      :string
    t.column "postal_code", :string
    t.column "country",     :string
  end

  add_index "geocodes", ["latitude"], :name => "geocodes_latitude_index"
  add_index "geocodes", ["longitude"], :name => "geocodes_longitude_index"
  add_index "geocodes", ["query"], :name => "geocodes_query_index", :unique => true

  create_table "geocodings", :force => true do |t|
    t.column "geocodable_id",   :integer
    t.column "geocode_id",      :integer
    t.column "geocodable_type", :string
  end

  add_index "geocodings", ["geocodable_id"], :name => "geocodings_geocodable_id_index"
  add_index "geocodings", ["geocodable_type"], :name => "geocodings_geocodable_type_index"
  add_index "geocodings", ["geocode_id"], :name => "geocodings_geocode_id_index"

  create_table "history", :force => true do |t|
    t.column "user_id",   :integer,  :default => 0, :null => false
    t.column "node_id",   :integer,  :default => 0, :null => false
    t.column "viewed_at", :datetime
  end

  create_table "linked_nodes", :force => true do |t|
    t.column "from_node_id", :integer, :default => 0, :null => false
    t.column "to_node_id",   :integer, :default => 0, :null => false
  end

  create_table "node_comment_statistics", :force => true do |t|
    t.column "node_id",                 :integer,  :default => 0, :null => false
    t.column "last_comment_created_at", :datetime
    t.column "last_comment_user_id",    :integer,  :default => 0, :null => false
    t.column "comment_count",           :integer
  end

  create_table "nodes", :force => true do |t|
    t.column "label",       :string,   :limit => 50, :default => ""
    t.column "body",        :text,                   :default => ""
    t.column "extended",    :text,                   :default => ""
    t.column "excerpt",     :text,                   :default => ""
    t.column "start_date",  :datetime
    t.column "end_date",    :datetime
    t.column "address",     :string,                 :default => ""
    t.column "city",        :string,                 :default => ""
    t.column "statecode",   :string,                 :default => ""
    t.column "postcode",    :string,                 :default => ""
    t.column "countrycode", :string,                 :default => ""
    t.column "user_id",     :integer,                :default => 0,  :null => false
    t.column "created_at",  :datetime
  end

  create_table "taggings", :force => true do |t|
    t.column "tag_id",        :integer
    t.column "taggable_id",   :integer
    t.column "taggable_type", :string
  end

  add_index "taggings", ["tag_id", "taggable_id", "taggable_type"], :name => "index_taggings_on_tag_id_and_taggable_id_and_taggable_type"

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

  add_index "tags", ["name"], :name => "index_tags_on_name"

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "activation_code",           :string,   :limit => 40
    t.column "activated_at",              :datetime
  end

end
